export const ROOMS = [
  { id: 'wohn', name: 'Wohnzimmer' },
  { id: 'kueche', name: 'Küche' },
  { id: 'kinder', name: 'Kinderzimmer' },
  { id: 'schlaf', name: 'Schlafzimmer' }
];

// mood: happy | thirsty | dark | cold | air | hungry -> steuert die
// simulierten Startmesswerte (ok / low / high je Metrik).
export const PLANTS = [
  { id: 'p1', name: 'Wilma', type: 'begonia', room: 'wohn', days: 148, bond: 4, sensor: '8F2A', mood: 'thirsty', wateredDaysAgo: 9,
    says: 'Meine Punkte sehen schon blass aus. Ein Schluck, bitte.' },
  { id: 'p2', name: 'Betti', type: 'begonia', room: 'wohn', days: 148, bond: 3, sensor: '3C77', mood: 'happy', wateredDaysAgo: 4,
    says: 'Wilma jammert, mir geht es prima. Nur damit du es weißt.' },
  { id: 'p3', name: 'Willi', type: 'pilea', room: 'wohn', days: 96, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 6,
    says: 'Ich sammle Sonne wie Münzen. Läuft gut.' },
  { id: 'p4', name: 'Ben', type: 'bamboo', room: 'wohn', days: 211, bond: 4, sensor: 'A104', mood: 'happy', wateredDaysAgo: 2,
    says: 'Ich rausche leise vor mich hin. Alles im Lot.' },
  { id: 'p5', name: 'Monti', type: 'monstera', room: 'wohn', days: 402, bond: 5, sensor: 'B920', mood: 'hungry', wateredDaysAgo: 3,
    says: 'Die Erde hier ist ausgelutscht. Ein bisschen Dünger und ich bin wieder wer.' },
  { id: 'p6', name: 'Ronny', type: 'strelitzia', room: 'wohn', days: 327, bond: 4, sensor: '5E31', mood: 'happy', wateredDaysAgo: 5,
    says: 'Breite Blätter, breites Grinsen. Weiter so.' },
  { id: 'p7', name: 'Billy', type: 'bonsai', room: 'wohn', days: 612, bond: 5, sensor: null, mood: 'happy', wateredDaysAgo: 3,
    says: 'Ich bin klein, aber ich bin alt. Respekt genügt.' },
  { id: 'p8', name: 'Alf', type: 'pothos', room: 'wohn', days: 134, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 7,
    says: 'Ich ranke, du guckst. Gutes Arrangement.' },
  { id: 'p9', name: 'Bob', type: 'sansevieria', room: 'wohn', days: 540, bond: 4, sensor: null, mood: 'happy', wateredDaysAgo: 21,
    says: 'Ich bin pflegeleicht bis zur Selbstaufgabe. Alles gut hier.' },
  { id: 'p10', name: 'Michi', type: 'coffee', room: 'kueche', days: 88, bond: 3, sensor: '7712', mood: 'thirsty', wateredDaysAgo: 8,
    says: 'Ausgerechnet ich bekomme hier nichts zu trinken. Ironie, oder?' },
  { id: 'p11', name: 'Pia', type: 'pilea', room: 'kueche', days: 64, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 5,
    says: 'Beste Aussicht auf den Kühlschrank. Zufrieden.' },
  { id: 'p12', name: 'Mandy', type: 'monstera', room: 'kueche', days: 176, bond: 4, sensor: '21C8', mood: 'happy', wateredDaysAgo: 4,
    says: 'Küchendampf ist mein Wellnessprogramm.' },
  { id: 'p13', name: 'Ralf', type: 'pothos', room: 'kueche', days: 119, bond: 2, sensor: null, mood: 'happy', wateredDaysAgo: 6,
    says: 'Ich hänge ab. Wörtlich.' },
  { id: 'p14', name: 'Melli', type: 'pothos', room: 'kueche', days: 119, bond: 2, sensor: null, mood: 'happy', wateredDaysAgo: 6,
    says: 'Ralf und ich machen Wettranken. Ich führe.' },
  { id: 'p15', name: 'Peps', type: 'pilea', room: 'kinder', days: 72, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 5,
    says: 'Hier ist immer was los. Ich mag das.' },
  { id: 'p16', name: 'Pepo', type: 'pilea', room: 'kinder', days: 72, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 5,
    says: 'Peps ist mein Zwilling. Wir sind beide gut drauf.' },
  { id: 'p17', name: 'Michel', type: 'monstera', room: 'kinder', days: 158, bond: 4, sensor: '9B30', mood: 'dark', wateredDaysAgo: 4,
    says: 'Hinter dem Regal sehe ich kaum meine eigenen Blätter.' },
  { id: 'p18', name: 'Princess', type: 'kingbegonia', room: 'kinder', days: 53, bond: 3, sensor: '4417', mood: 'air', wateredDaysAgo: 2,
    says: 'Die Luft hier ist wie ein Föhn. Etwas feuchter, bitte.' },
  { id: 'p19', name: 'Kaka', type: 'cactus', room: 'schlaf', days: 430, bond: 4, sensor: null, mood: 'happy', wateredDaysAgo: 28,
    says: 'Ich brauche nichts. Wirklich nichts.' },
  { id: 'p20', name: 'Kaki', type: 'cactus', room: 'schlaf', days: 430, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 28,
    says: 'Was Kaka sagt. Nur stacheliger.' },
  { id: 'p21', name: 'Gigi', type: 'rubber', room: 'schlaf', days: 289, bond: 4, sensor: 'C205', mood: 'happy', wateredDaysAgo: 9,
    says: 'Meine Blätter glänzen. Danke fürs Abstauben.' },
  { id: 'p22', name: 'Elli', type: 'pothos', room: 'schlaf', days: 101, bond: 3, sensor: null, mood: 'happy', wateredDaysAgo: 7,
    says: 'Nachtruhe wird hier großgeschrieben. Sehr angenehm.' }
];
